workspace = { members = ["tr_reader", "tr_derive"] }

[package]
name = "tr_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1", features = ["dynamic_linking"] }
smooth-bevy-cameras = "0.10.0"
leafwing-input-manager = "0.11.2"
num-traits = "0.2.17"
itertools = "0.12.1"
glam-traits = { git = "https://github.com/Ababwa/glam-traits.git", branch = "glam_fork" }
tr_reader = { path = "tr_reader" }
