[workspace]
members = ["shared", "tr_readable", "tr_derive", "tr_model", "tr_tool"]
resolver = "2"

[workspace.dependencies]
glam = "0.29.0"
glam-traits = { version = "0.2.0", features = ["ext"] }
shared = { path = "shared" }
