[workspace]
members = ["tr_model", "tr_derive", "shared", "tool2", "tr_readable"]
resolver = "2"

[workspace.dependencies]
glam = "0.29.0"
glam-traits = { version = "0.2.0", features = ["ext"] }
shared = { path = "shared" }
