[package]
name = "tr_readable"
version = "0.1.0"
edition = "2021"

[dependencies]
compress = { version = "0.2.1", default-features = false, features = ["zlib"] }
shared = { path = "../shared" }
tr_derive = { path = "../tr_derive" }
