[package]
name = "tr_readable"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.1.2", default-features = false, features = ["zlib-rs"] }
tr_derive = { path = "../tr_derive" }
