[package]
name = "tr_readable"
version = "0.1.0"
edition = "2021"

[dependencies]
compress = "0.2.1"
glam = { workspace = true }
glam-traits = { workspace = true }
nonmax = { workspace = true }
reinterpret = { workspace = true }
tr_derive = { path = "../tr_derive" }
